from __future__ import annotations

# Versioned clinical/domain configuration for preprocessing.
# Keep merge rules, drop decisions, and pipeline control flow in preprocess_pipeline.py.

CONFIG_NAME = "default_preprocess_config"
CONFIG_VERSION = "0.1.0"

IQR_DEFAULT_MULTIPLIER = 3.0

SIGNOS_NUMERIC_COLUMNS = [
    "temperatura",
    "frec_respiratoria",
    "frec_cardiaca",
    "tension_arterial",
    "saturacion_o2",
]

SEPSIS_NUMERIC_COLUMNS = [
    "lactato_serico",
    "proteina_c_reactiva",
    "sofa",
    "respiracion",
    "snc_glasgow",
    "cardiovascular",
    "bilirrubina",
    "plaquetas",
    "creatinina",
    "qsofa"
]

SIGNOS_THRESHOLDS = {
    "temperatura_fever_min": 38.0,
    "temperatura_normal_min": 36.0,
    "tension_arterial_hypotension_max": 100.0,
    "frec_respiratoria_taquipnea_min": 20.0,
    "frec_cardiaca_taquicardia_min": 90.0,
    "saturacion_o2_hipoxemia_max": 90.0,
}

SINTOMA_SHORT_DURATION_MAX_DAYS = 7
PRIOR_ANTIBIOTIC_WINDOW_DAYS = 90

SEPSIS_OUTLIER_COLUMNS = ["proteina_c_reactiva"]
SIGNOS_OUTLIER_COLUMNS = [
    "temperatura",
    "frec_respiratoria",
    "frec_cardiaca",
    "tension_arterial",
    "saturacion_o2",
]
SEPSIS_QUARTILE_RECODE_COLUMNS = SEPSIS_OUTLIER_COLUMNS
SIGNOS_QUARTILE_RECODE_COLUMNS = SIGNOS_OUTLIER_COLUMNS

FECHA_INFECCION_CORRECTIONS = {
    "323-05-01": "2023-05-01",
}

MICROORGANISM_LABEL_MAP = {
    "NOEB": "_Other bacteria",
    "VIRUS": "_Virus",
    "FUNGUS": "_Fungi",
    "OEB": "_Enterobacteria",
    "ECOLI": "Escherichia coli",
    "SA": "Staphylococcus aureus",
    "PSA": "Pseudomonas aeruginosa",
    "KP": "Klebsiella pneumoniae",
    "SP": "Streptococcus pneumoniae",
    "EC": "Enterococcus",
}

MICROORGANISM_BROAD_GROUP_MAP = {
    "Escherichia coli": "Bacilo gram-",
    "Klebsiella pneumoniae": "Bacilo gram-",
    "_Enterobacteria": "Bacilo gram-",
    "Pseudomonas aeruginosa": "Bacilo gram-",
    "Staphylococcus aureus": "Coco gram+",
    "Streptococcus pneumoniae": "Coco gram+",
}

HEMOCULTURE_MICROORGANISM_GNB_CLASS = {
    "Abiotrophia defectiva": "other_etiology",
    "Acinetobacter haemolyticus": "GNB",
    "Acinetobacter pittii": "GNB",
    "Aerococcus urinae": "other_etiology",
    "Anaerococcus vaginalis": "other_etiology",
    "Bacteroides fragilis": "GNB",
    "Bacteroides thetaiotaomicron": "GNB",
    "Brachybacterium muris": "other_etiology",
    "Brevibacillus agri": "other_etiology",
    "Brevibacterium epidermidis": "other_etiology",
    "Campylobacter fetus": "GNB",
    "Campylobacter jejuni": "GNB",
    "Candida albicans": "other_etiology",
    "Candida glabrata": "other_etiology",
    "Candida parapsilosis": "other_etiology",
    "Capnocytophaga canimorsus": "GNB",
    "Citrobacter farmeri": "GNBSelected",
    "Citrobacter freundii": "GNBSelected",
    "Citrobacter koseri": "GNBSelected",
    "Citrobacter youngae": "GNBSelected",
    "Clostridium paraputrificum": "other_etiology",
    "Clostridium perfringens": "other_etiology",
    "Corynebacterium afermentans": "other_etiology",
    "Corynebacterium jeikeium": "other_etiology",
    "Corynebacterium mucifaciens": "other_etiology",
    "Corynebacterium striatum": "other_etiology",
    "Eggerthella lenta": "other_etiology",
    "Enterobacter asburiae": "GNBSelected",
    "Enterobacter cloacae": "GNBSelected",
    "Enterococcus": "other_etiology",
    "Enterococcus durans": "other_etiology",
    "Enterococcus faecalis": "other_etiology",
    "Enterococcus faecium": "other_etiology",
    "Escherichia coli": "GNBSelected",
    "Fusobacterium nucleatum": "GNB",
    "Haemophilus influenzae": "GNB",
    "Klebsiella aerogenes": "GNBSelected",
    "Klebsiella oxytoca": "GNBSelected",
    "Klebsiella pneumoniae": "GNBSelected",
    "Klebsiella variicola": "GNBSelected",
    "Listeria monocytogenes": "other_etiology",
    "Micrococcus luteus": "other_etiology",
    "Moraxella osloensis": "GNB",
    "Morganella morganii": "GNBSelected",
    "NEGATIVE": "NEGATIVE",
    "Neisseria meningitidis": "other_etiology",
    "Pantoea agglomerans": "GNBSelected",
    "Parvimonas micra": "other_etiology",
    "Pasteurella multocida": "GNB",
    "Peptoniphilus harei": "other_etiology",
    "Prevotella denticola": "GNB",
    "Proteus mirabilis": "GNBSelected",
    "Providencia rettgeri": "GNBSelected",
    "Providencia stuartii": "GNBSelected",
    "Pseudomonas aeruginosa": "GNBSelected",
    "Pseudomonas stutzeri": "GNB",
    "Raoultella ornithinolytica": "GNBSelected",
    "Roseomonas mucosa": "GNB",
    "Salmonella enterica": "GNBSelected",
    "Schaalia odontolytica": "other_etiology",
    "Serratia marcescens": "GNBSelected",
    "Staphylococcus aureus": "other_etiology",
    "Staphylococcus capitis": "other_etiology",
    "Staphylococcus epidermidis": "other_etiology",
    "Staphylococcus haemolyticus": "other_etiology",
    "Staphylococcus hominis": "other_etiology",
    "Staphylococcus saprophyticus": "other_etiology",
    "Streptococcus agalactiae": "other_etiology",
    "Streptococcus anginosus": "other_etiology",
    "Streptococcus beta - hemolítico": "other_etiology",
    "Streptococcus constellatus": "other_etiology",
    "Streptococcus dysgalactiae": "other_etiology",
    "Streptococcus equi": "other_etiology",
    "Streptococcus equinus": "other_etiology",
    "Streptococcus gallolyticus": "other_etiology",
    "Streptococcus lutetiensis": "other_etiology",
    "Streptococcus mitis": "other_etiology",
    "Streptococcus oralis": "other_etiology",
    "Streptococcus parasanguinis": "other_etiology",
    "Streptococcus pneumoniae": "other_etiology",
    "Streptococcus pyogenes": "other_etiology",
    "Streptococcus sanguinis": "other_etiology",
    "Thomasclavelia ramosa": "other_etiology",
    "Vibrio parahaemolyticus": "GNB",
    "_Enterobacteria": "GNBSelected",
    "_Fungi": "other_etiology",
    "_Other bacteria": "other_etiology",
    "cocobacilo anaeróbico grampositivo": "other_etiology",
    "familia Enterobacteriaceae": "GNBSelected",
    "género Arthrobacter": "other_etiology",
    "género Bacteroides": "GNB",
    "género Brevibacillus": "other_etiology",
    "género Elizabethkingia": "GNB",
    "género Enterobacter": "GNBSelected",
    "género Micrococcus": "other_etiology",
    "género Morganella": "GNBSelected",
    "género Peptoniphilus": "other_etiology",
    "género Proteus": "GNBSelected",
    "género Salmonella": "GNBSelected",
    "género Staphylococcus": "other_etiology",
    "género Streptococcus": "other_etiology",
}

FENOTYPE_DRUG_TRANSLATIONS = {
    "amoxicilina/clavulánico": "amoxicillin and beta-lactamase inhibitor",
    "ciprofloxacino": "ciprofloxacin",
    "ceftrixona o cefotaxima": "ceftriaxone",
    "ceftazidima": "ceftazidime",
    "piperacilina/tazobactam": "piperacillin and beta-lactamase inhibitor",
    "cefepima": "cefepime",
    "ampicilina o penicilina": "ampicillin",
    "meticilina": "cloxacillin",
    "meropenem": "meropenem",
    "ceftazidima/avibactam": "ceftazidime and beta-lactamase inhibitor",
    "ceftolozano/tazobactam": "ceftolozane and beta-lactamase inhibitor",
    "vancomicina": "vancomycin",
}

HEMOCULTIVO_COINFECTION_RESOLUTION_GROUPS = {
    50: "Escherichia coli",
    419: "Staphylococcus aureus",
    770: "Escherichia coli",
    780: "Escherichia coli",
    1214: "Klebsiella pneumoniae",
    1309: "Escherichia coli",
    1886: "Klebsiella pneumoniae",
    1925: "Escherichia coli",
    1960: "Enterococcus",
    1977: "Escherichia coli",
    2274: "Escherichia coli",
    2294: "NEGATIVE",
    2634: "Escherichia coli",
    2638: "Klebsiella pneumoniae",
    2681: "Klebsiella pneumoniae",
    2845: "Escherichia coli",
    2971: "Escherichia coli",
    2983: "Escherichia coli",
    3019: "Escherichia coli",
    3087: "Escherichia coli",
    3167: "Escherichia coli",
    3352: "Escherichia coli",
    3479: "Escherichia coli",
    3819: "_Enterobacteria",
    1247: "_Enterobacteria",
    2640: "Escherichia coli",
    133: "Pseudomonas aeruginosa",
    1881: "Escherichia coli",
    420: "_Other bacteria",
    1110: "_Other bacteria",
    1239: "Klebsiella pneumoniae",
    1310: "Escherichia coli",
    1379: "Pseudomonas aeruginosa",
    1906: "_Fungi",
    2041: "Escherichia coli",
    2284: "_Other bacteria",
    2647: "_Enterobacteria",
    2848: "Escherichia coli",
    3116: "Escherichia coli",
    447: "Escherichia coli",
    607: "_Enterobacteria",
    668: "Klebsiella pneumoniae",
    760: "Escherichia coli",
    956: "_Other bacteria",
    1089: "Staphylococcus aureus",
    1170: "Escherichia coli",
    1228: "Escherichia coli",
    1286: "Escherichia coli",
    1308: "Klebsiella pneumoniae",
    1311: "_Fungi",
    1322: "_Enterobacteria",
    1355: "Escherichia coli",
    1663: "Escherichia coli",
    1717: "NEGATIVE",
    1865: "_Other bacteria",
    1885: "_Enterobacteria",
    1893: "Pseudomonas aeruginosa",
    1967: "Escherichia coli",
    1975: "Escherichia coli",
    1976: "_Enterobacteria",
    2336: "Escherichia coli",
    2441: "Escherichia coli",
    2469: "Escherichia coli",
    2926: "Klebsiella pneumoniae",
    2974: "Klebsiella pneumoniae",
    3457: "_Enterobacteria",
    1954: "Escherichia coli",
    2016: "Escherichia coli",
    2810: "Escherichia coli",
    2840: "Staphylococcus aureus",
    429: "_Other bacteria",
    473: "Escherichia coli",
    480: "Staphylococcus aureus",
    766: "NEGATIVE",
    797: "_Enterobacteria",
    1303: "NEGATIVE",
    1777: "_Enterobacteria",
    1839: "Escherichia coli",
    1850: "Escherichia coli",
    1873: "_Enterobacteria",
    2308: "NEGATIVE",
    2335: "_Enterobacteria",
    2341: "Staphylococcus aureus",
    2513: "_Enterobacteria",
    2873: "Klebsiella pneumoniae",
    462: "Escherichia coli",
    562: "Escherichia coli",
    599: "Escherichia coli",
    759: "_Enterobacteria",
    871: "Pseudomonas aeruginosa",
    961: "Escherichia coli",
    1052: "_Enterobacteria",
    1241: "Escherichia coli",
    1246: "Klebsiella pneumoniae",
    1333: "Escherichia coli",
    1658: "Escherichia coli",
    1776: "Escherichia coli",
    1875: "Escherichia coli",
    1956: "_Enterobacteria",
    1966: "Escherichia coli",
    2017: "Escherichia coli",
    2303: "Staphylococcus aureus",
    2321: "Escherichia coli",
    2354: "Klebsiella pneumoniae",
    2408: "Escherichia coli",
    2467: "Escherichia coli",
    2479: "Klebsiella pneumoniae",
    2493: "Pseudomonas aeruginosa",
    2533: "Escherichia coli",
    2625: "Escherichia coli",
    2663: "Escherichia coli",
    2715: "Escherichia coli",
    2813: "Klebsiella pneumoniae",
    3491: "_Enterobacteria",
    3675: "Klebsiella pneumoniae",
    426: "Staphylococcus aureus",
}

ANTIMICROBIAL_GROUPS = [
    ("AMIKACINA", "Aminoglucosidos", "amikacin"),
    ("AMOXICILINA", "Penicilinas", "amoxicillin"),
    ("AMOXICILINA / CLAVULANICO", "Penicilinas", "amoxicillin and beta-lactamase inhibitor"),
    ("AMPICILINA", "Penicilinas", "ampicillin"),
    ("AZITROMICINA", "Macrolidos", "azithromycin"),
    ("AZTREONAM", "Monobactamicos", "aztreonam"),
    ("BENCILPENICILINA", "Penicilinas", None),
    ("BENCILPENICILINA-BENZATINA", "Penicilinas", None),
    ("CEFADROXILO MONOHIDRATO", "Cefalosporinas 1 gen", "cefadroxil"),
    ("CEFAZOLINA", "Cefalosporinas 1 gen", "cefazolin"),
    ("CEFEPIMA", "Cefalosporinas 3/4 gen", "cefepime"),
    ("CEFIDEROCOL", "Cefalosporinas 3/4 gen", None),
    ("CEFIXIMA", "Cefalosporinas 3/4 gen", "cefixime"),
    ("CEFOTAXIMA", "Cefalosporinas 3/4 gen", "cefotaxime"),
    ("CEFTAROLINA FOSAMILO", "Cefalosporinas 2 gen", "ceftaroline fosamil"),
    ("CEFTAZIDIMA", "Cefalosporinas 3/4 gen", "ceftazidime"),
    ("CEFTAZIDIMA / AVIBACTAM", "Cefalosporinas 3/4 gen", "ceftazidime and beta-lactamase inhibitor"),
    ("CEFTOLOZANO / TAZOBACTAM", "Cefalosporinas 3/4 gen", "ceftolozane and beta-lactamase inhibitor"),
    ("CEFTRIAXONA", "Cefalosporinas 3/4 gen", "ceftriaxone"),
    ("CEFUROXIMA", "Cefalosporinas 2 gen", "cefuroxime"),
    ("CIPROFLOXACINO", "Quinolonas", "ciprofloxacin"),
    ("CLARITROMICINA", "Macrolidos", "clarithromycin"),
    ("CLINDAMICINA", "Lincosamidas", "clindamycin"),
    ("CLOXACILINA", "Penicilinas", "cloxacillin"),
    ("COLISTIMETATO DE SODIO", "Polimixinas", None),
    ("DALBAVANCINA", "Glicopéptidos", "dalbavancin"),
    ("DAPTOMICINA", "Lipopeptidos", "daptomycin"),
    ("DOXICICLINA", "Tetraciclinas", "doxycycline"),
    ("ERITROMICINA", "Macrolidos", "erythromycin"),
    ("ERTAPENEM", "Carbapenemas", "ertapenem"),
    ("FIDAXOMICINA", "Macrolidos", None),
    ("FOSFOMICINA", "Fosfomicina", "fosfomycin"),
    ("FOSFOMICINA-TROMETAMOL", "Fosfomicina", "fosfomycin"),
    ("GENTAMICINA", "Aminoglucosidos", "gentamicin"),
    ("IMIPENEM", "Carbapenemas", "imipenem and cilastatin"),
    ("IMIPENEM/RELEBACTAM", "Carbapenemas", None),
    ("LEVOFLOXACINO", "Quinolonas", "levofloxacin"),
    ("LINEZOLID", "Lincosamidas", "linezolid"),
    ("MEROPENEM", "Carbapenemas", "meropenem"),
    ("METRONIDAZOL", "Metronidazol", "metronidazole"),
    ("MINOCICLINA", "Minociclina", None),
    ("MOXIFLOXACINO", "Quinolonas", "moxifloxacin"),
    ("NITROFURANTOINA", "Nitrofurantoina", "nitrofurantoin"),
    ("NORFLOXACINO", "Quinolonas", "norfloxacin"),
    ("PIPERACILINA / TAZOBACTAM", "Penicilinas", "piperacillin and beta-lactamase inhibitor"),
    ("POSACONAZOL", "Azoles", "posaconazole"),
    ("SULFADIAZINA", "Sulfonamidas", "sulfadiazine"),
    ("SULFAMETOXAZOL / TRIMETOPRIMA", "Sulfonamidas", "sulfamethoxazole and trimethoprim"),
    ("TRIMETOPRIMA", "Sulfonamidas", "trimethoprim"),
    ("TEICOPLANINA", "Glicopéptidos", "teicoplanin"),
    ("TIGECICLINA", "Tigeciclina", "tigecycline"),
    ("TOBRAMICINA", "Aminoglucosidos", "tobramycin"),
    ("VANCOMICINA", "Glicopéptidos", "vancomycin"),
    ("A", "Tetraciclinas", "tetracycline"),
    ("A", "Cefalosporinas 3/4 gen", "cefditoren"),
    ("A", "Carbapenemas", "meropenem and vaborbactam"),
    ("A", "Cefalosporinas 1 gen", "cefalexin"),
    ("A", "Cefalosporinas 2 gen", "cefoxitin"),
    ("A", "AntiTuberculoso", "rifampicin"),
    ("A", "AntiTuberculoso", "rifabutin"),
    ("A", "AntiTuberculoso", "isoniazid"),
    ("A", "AntiTuberculoso", "pyrazinamide"),
    ("A", "AntiTuberculoso", "ethambutol"),
    ("B", "Azoles", "isavuconazole"),
    ("B", "Azoles", "fluconazole"),
    ("B", "Azoles", "itraconazole"),
    ("B", "Azoles", "voriconazole"),
    ("B", "Equinocandinas", "caspofungin"),
    ("B", "Equinocandinas", "micafungin"),
    ("B", "Equinocandinas", "anidulafungin"),
]


def as_dict() -> dict:
    return {
        "CONFIG_NAME": CONFIG_NAME,
        "CONFIG_VERSION": CONFIG_VERSION,
        "IQR_DEFAULT_MULTIPLIER": IQR_DEFAULT_MULTIPLIER,
        "SIGNOS_NUMERIC_COLUMNS": SIGNOS_NUMERIC_COLUMNS,
        "SEPSIS_NUMERIC_COLUMNS": SEPSIS_NUMERIC_COLUMNS,
        "SIGNOS_THRESHOLDS": SIGNOS_THRESHOLDS,
        "SINTOMA_SHORT_DURATION_MAX_DAYS": SINTOMA_SHORT_DURATION_MAX_DAYS,
        "PRIOR_ANTIBIOTIC_WINDOW_DAYS": PRIOR_ANTIBIOTIC_WINDOW_DAYS,
        "SEPSIS_OUTLIER_COLUMNS": SEPSIS_OUTLIER_COLUMNS,
        "SIGNOS_OUTLIER_COLUMNS": SIGNOS_OUTLIER_COLUMNS,
        "SEPSIS_QUARTILE_RECODE_COLUMNS": SEPSIS_QUARTILE_RECODE_COLUMNS,
        "SIGNOS_QUARTILE_RECODE_COLUMNS": SIGNOS_QUARTILE_RECODE_COLUMNS,
        "FECHA_INFECCION_CORRECTIONS": FECHA_INFECCION_CORRECTIONS,
        "MICROORGANISM_LABEL_MAP": MICROORGANISM_LABEL_MAP,
        "MICROORGANISM_BROAD_GROUP_MAP": MICROORGANISM_BROAD_GROUP_MAP,
        "HEMOCULTURE_MICROORGANISM_GNB_CLASS": HEMOCULTURE_MICROORGANISM_GNB_CLASS,
        "FENOTYPE_DRUG_TRANSLATIONS": FENOTYPE_DRUG_TRANSLATIONS,
        "HEMOCULTIVO_COINFECTION_RESOLUTION_GROUPS": HEMOCULTIVO_COINFECTION_RESOLUTION_GROUPS,
        "ANTIMICROBIAL_GROUPS": ANTIMICROBIAL_GROUPS,
    }
